---
title: "Uitbreiding visiegebied Duivenbos  \nGevolgen voor buurtbewoners"
date: today
authors: "Bernadette Michiels  \nKarel De Tremerie"
title-block-banner: true
---



# Wat zijn de gevolgen voor de buurtbewoners indien deze plannen worden goedgekeurd? 

# Waarom deze bijdrage?

Via sociale, lokale en regionale nieuwsmedia mengen agitatoren, vaak zonder gedegen kennis van het dossier en aangestuurd door de Boerenbond en de agro-industrie, zich in het debat over de uitbreiding van het visiegebied van het Duivenbos. Zoals het boerenprotest van de voorbije weken heeft aangetoond, is hun doel de besluitvorming te domineren. Daarbij willen zij gesprekspartners als Natuurpunt uit de overlegstructuren verwijderen.

Om Natuurpunt in een negatief daglicht te stellen, framen zij de Uitbreidingsplannen Duivenbos met halve waarheden en leugens. Het is daarom belangrijk om duidelijk te maken waarom deze uitbreiding meer dan logisch is en zelfs op Vlaams en gemeentelijk niveau als van strategisch belang wordt beschouwd. Laten we ons daarbij baseren op feiten, niet op slogans.


# Impact op de belanghebbenden

Bepaalde landbouwers hebben belang bij een ongewijzigd landbouwbeleid. In Herzele ontvangen Transparantie – Verordening (EG) nr. 1306/2013 (art. 111 e.v.) en de uitvoeringsvordering V(EU) nr. 908/2014 (art. 57 e.v.).


